name: Pull Request Pipeline

on:
  # manual trigger 
  #workflow_dispatch:

  #Runs after merging the pull request 
  push:  
    types: [labeled]

  # Runs after creating pull request   
  # pull_request:
  #   types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    # confdition to trigger only if the trigger lable is selected in pull request 
    if: contains(github.event.pull_request.labels.*.name, 'Trigger')
    steps:
      - uses: actions/checkout@v3
      - name: Echo
        run: echo "Creating artifact"
